# Generated by Django 4.2.11 on 2026-08-24 18:56

import api.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_feedpost_team_userfollow_teammember_feedshare_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", api.models.UserManager()),
            ],
        ),
    ]
