# Generated by Django 4.2.11 on 2026-08-26 11:43
# Hand-edited: the auto-generated AlterField for Team.college (CharField -> ForeignKey)
# would silently drop existing free-text college values on SQLite, since the underlying
# column is renamed (college -> college_id) and Django can't cast text into a FK id.
# This version adds a temp FK, backfills it from the old text via RunPython, then swaps
# it in - dropping and recreating the index on the correct side of the column swap.

from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify
import uuid


def migrate_team_college_text_to_fk(apps, schema_editor):
    Team = apps.get_model('api', 'Team')
    College = apps.get_model('api', 'College')

    seen = {}
    for team in Team.objects.all():
        name = (team.college or '').strip()
        if not name:
            continue
        key = name.lower()
        college = seen.get(key)
        if not college:
            college = College.objects.filter(name__iexact=name).first()
            if not college:
                base_slug = slugify(name) or 'college'
                slug = base_slug
                suffix = 2
                while College.objects.filter(slug=slug).exists():
                    slug = f'{base_slug}-{suffix}'
                    suffix += 1
                college = College.objects.create(name=name, slug=slug)
            seen[key] = college
        team.college_fk = college
        team.save(update_fields=['college_fk'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='college_logos/')),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('email_domain', models.CharField(blank=True, help_text='e.g. xyzcollege.edu - used for student verification', max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        # Drop the old index on the text 'college' column before we touch that column.
        migrations.RemoveIndex(
            model_name='team',
            name='api_team_college_170ce4_idx',
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to='api.team'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_verified_student',
            field=models.BooleanField(default=False, help_text='Verified via college email/ID'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['name'], name='api_college_name_664363_idx'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='api.college'),
        ),
        # --- Team.college: text -> real College FK, without losing existing data ---
        migrations.AddField(
            model_name='team',
            name='college_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='api.college'),
        ),
        migrations.RunPython(migrate_team_college_text_to_fk, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='team',
            name='college',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='college_fk',
            new_name='college',
        ),
        # Recreate the index now that 'college' is the FK column.
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['college'], name='api_team_college_6fa75a_idx'),
        ),
    ]
