# Generated by Django 4.2.11 on 2026-09-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_college_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="behance_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="branch",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="career_objective",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="college_id_document",
            field=models.FileField(blank=True, null=True, upload_to="college_ids/"),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="current_year",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="dribbble_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="experience",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="gender",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="graduation_year",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="languages_known",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="student_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="tech_stack",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="university_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
