# Generated by Django 4.2.11 on 2026-09-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_studentprofile_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web_dev', 'Web Development'), ('mobile_dev', 'Mobile Development'), ('design', 'Design'), ('data_science', 'Data Science'), ('devops', 'DevOps'), ('other', 'Other')], max_length=100),
        ),
    ]
